export default {
  baseURL: '',
  background: '#000000',
  player: window.location.origin + '/images/player.png?=1000',
  coin: 'https://assets.bitboy.games/rush-map-editor/coin.png',
  brick: 'https://assets.bitboy.games/rush-map-editor/store.png',
  level: 
  // [
  //   '                                                                                ',
  //   '                                                                                ',
  //   '                                                                                ',
  //   '                                                                                ',
  //   '                                                                                ',
  //   '                                                                  xxx           ',
  //   '                                                   xx      xx    xx!xx          ',
  //   '                                    o o      xx                  x!!!x          ',
  //   '                                                                 xx!xx          ',
  //   '                                   xxxxx                          xvx           ',
  //   '                                                                            xx  ',
  //   '  xx                                      o o                                x  ',
  //   '  x                     o                                                    x  ',
  //   '  x                                      xxxxx                             o x  ',
  //   '  x          xxxx       o                                                    x  ',
  //   '  x  @       x  x                                                xxxxx       x  ',
  //   '  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ',
  //   '                              x   x                  x     x                    ',
  //   '                              x!!!x                  x!!!!!x                    ',
  //   '                              x!!!x                  x!!!!!x                    ',
  //   '                              xxxxx                  xxxxxxx                    ',
  //   '                                                                                ',
  //   '                                                                                '
  // ],
  // ["                                                                                 ",
  //   "                                                                                 ",
  //   "                      x                                                          ",
  //   "                 ooooox                                                v         ",
  //   "                      x                                                          ",
  //   "          o      ooooox o o o o=x                                                ",
  //   "          o  ooooxxxxxx o o o o x                                                ",
  //   "          ov|oooox    x o o o o=x      =  oooo      =                oo= o o o o ",
  //   "          o  oooox    x o o o o x         oooo     oo        oo      ooxxx       ",
  //   "          x xxxxxx    x o=o o o x         xxxx     oo     oo xx   oo xx    xx!xx ",
  //   "   =     ox v         xxxxxxxxxxx   ooooo      ooooxx!    xx      oo          x!!",
  //   "  oo     ox                         ooooo      oooo  v            xx!xx          ",
  //   "  oo     ox                         xxxxx                          xvx           ",
  //   "  oo     xx                                   ooxxxooo    =                  o   ",
  //   "  xx  ooo               o  o o                                               o x ",
  //   "  x  |xxxxx  oooo       oooooo               xxxxxxx               o         o   ",
  //   "  x          oooo    v  o o  o            oo              ooo      o       o x o ",
  //   "  x          xxxx       o o  o    ooo                              o       o x o ",
  //   "  x @        x  x         =            =               =         xxxxx     o x o ",
  //   "  xxxxxxx o x    xxxx xxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx",
  //   "        x o x                    x   x                  x     x                  ",
  //   "        x o x                    x!!!x                  x!!!!!x                  ",
  //   "        x o x                    x!!!x                  x!!!!!x                  ",
  //   "        xxxxx                    xxxxx                  xxxxxxx                  ",
  //   "                                                                                 ",
  //   "                                                                                 "
  // ],
  [
    "                                xxxxxxxxxx                                      ",
    "                                x    |   x                                      ",
    "                                x  o   o=x                                      ",
    "                                         x                                      ",
    "                                         x                                      ",
    "                                 xxxxxxxxx                                      ",
    "                                  x     x                                       ",
    "                                 x x   x x                                      ",
    "                                x         x                                     ",
    "                               xxxxxxxxxxxxx                                    ",
    "                                 xxxxxxxxx                                      ",
    "                                   xxxxx                                        ",
    "                                    xxx                                         ",
    "                                xxxxxxxxxxx                                     ",
    "  xxxxxxvxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                     o                        |              x  ",
    "  o            o                     x=                                     =x  ",
    "  x          x  x                                              o        ooo  xo!",
    "!oxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx  xxxxxxxxxx  xxxxxxxxxxo!",
    " oxxxxvxxxxxxx!!xxxxxxxxxxxxxxx x x=                 =xx= o =o o =xx= o   o =xo ",
    " o     xxxxxxx! xxxxxxxxxxxxxxx o!x                                             ",
    "         o  o   o                                                               ",
    "   @                                                                            ",
    "  xxxxxxxxxxxx xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxx  xxxxxxxxxx  ",
  ]
}
